# Author: Yusef Karim
# To install cargo-make run: cargo install cargo-make
[env]
RELEASE_EXE   = "target/thumbv7m-none-eabi/debug/${CARGO_MAKE_CRATE_NAME}"
RELEASE_BIN   = "target/thumbv7m-none-eabi/debug/${CARGO_MAKE_CRATE_NAME}.bin"
TRIPLE 		  = "arm-none-eabi"
GDB			  = "${TRIPLE}-gdb"
OBJCOPY		  = "${TRIPLE}-objcopy"
OPENOCD_TRGT  = "-f target/stm32f1x.cfg"
OPENOCD_INTF  = "-f interface/stlink-v2.cfg"
OPENOCD_CMD	  = "openocd ${OPENOCD_INTF} ${OPENOCD_TRGT} -c"
DFU_EXE		  = "/usr/bin/dfu-util"


[tasks.flash]
description = "Flash binary file using STlink debugger, assumes memory address 0x08000000"
dependencies = ["build", "bin"]
script = ["${OPENOCD_CMD} \"program ${RELEASE_BIN} reset exit 0x08000000\""]


[tasks.boot]
description = "Flash bootloader binary included with this project"
script = ["${OPENOCD_CMD} \"program ./generic_boot20_pc13.bin reset exit 0x08000000\""]


[tasks.load]
description = "Use DFU utilility to upload code via bootloader (requires reset)"
dependencies = ["build", "bin"]
script = ["sudo ${DFU_EXE} -d 1EAF:003 -a 2 -D ${RELEASE_BIN} -R"]


[tasks.bin]
description = "Copies compiled executable to raw binary using objcopy"
dependencies = ["build"]
script = ["${OBJCOPY} -O binary ${RELEASE_EXE} ${RELEASE_BIN}"]


[tasks.erase]
description = "Uses OpenOCD to erase all flash memory on target board"
script = ["${OPENOCD_CMD} \"init; reset halt; stm32f1x mass_erase 0; exit\""]


[tasks.host]
description = "Use semi-hosting to see debug output, requires STlink debugger"
script = ["${OPENOCD_CMD} \"init; arm semihosting enable\""]
